version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_keycloak
      - MARIADB_DATABASE=bitnami_keycloak
    volumes:
      - 'mariadb_data:/bitnami/mariadb'