version: '2'
services:
  logstash-oss:
    image: docker.io/bitnami/logstash-oss:latest
    ports:
      - "5044:5044"
    volumes:
      - 'logstash_data:/bitnami/logstash'
    environment:
      - LOGSTASH_CONF=logstash.conf
      - LOGSTASH_PLUGINS=logstash-input-beats,logstash-output-elasticsearch
      - LOGSTASH_ELASTICSEARCH_HOST=elasticsearch
      - LOGSTASH_ELASTICSEARCH_PORT_NUMBER=9200
      - LOGSTASH_ELASTICSEARCH_USER=elastic
      - LOGSTASH_ELASTICSEARCH_PASSWORD=bitnami
      - LOGSTASH_ELASTICSEARCH_INDEX=logstash
      - LOGSTASH_ELASTICSEARCH_SSL_ENABLED=false
      - LOGSTASH_ELASTICSEARCH_SSL_VERIFICATION_MODE=certificate
      - LOGSTASH_ELASTICSEARCH_SSL_CERTIFICATE_VERIFICATION=false
      - LOGSTASH_ELASTICSEARCH_SSL_CERTIFICATE=/certs/cert.pem
      - LOGSTASH_ELASTICSEARCH_SSL_KEY=/certs/key.pem
      - LOGSTASH_ELASTICSEARCH_SSL_KEY_PASSPHRASE=bitnami
      - LOGSTASH_ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITIES=/certs/ca.pem
      - LOGSTASH_ELASTICSEARCH_SSL_VERSION=TLSv1_2
      - LOGSTASH_ELASTICSEARCH_SSL_CIPHERS=TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256
      - LOGSTASH_ELASTICSEARCH_SSL_CURVE_NAME=secp384r1
      - LOGSTASH_ELASTICSEARCH_SSL_VERIFY_HOSTNAME=false
      - LOGSTASH_ELASTICSEARCH_INDEX_DATE_PATTERN=YYYY.MM.dd
      - LOGSTASH_ELASTICSEARCH_PIPELINE=main
      - LOGSTASH_ELASTICSEARCH_TEMPLATE_NAME=logstash
      - LOGSTASH_ELASTICSEARCH_TEMPLATE_PATTERN=logstash-*
      - LOGSTASH_ELASTICSEARCH_TEMPLATE_FILE=/opt/bitnami/logstash/templates/logstash-template.json
      - LOGSTASH_ELASTICSEARCH_TEMPLATE_OVERWRITE=true
      - LOGSTASH_ELASTICSEARCH_TEMPLATE_APPEND=false
      - LOGSTASH_ELASTICSEARCH_TEMPLATE_PRIORITY=0
      - LOGSTASH_ELASTICSEARCH_TEMPLATE_VERSION=1