version: '3'
services:
  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "14250:14250"
      - "4317:4317"
    environment:
        COLLECTOR_ZIPKIN_HTTP_PORT: 9411
        COLLECTOR_ZIPKIN_HTTP_HOST: jaeger