version: '2'
services:
  prometheus:
    image: docker.io/bitnami/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - 'prometheus_data:/bitnami/prometheus'
    environment:
      - PROMETHEUS_CONF=prometheus.yml
      - PROMETHEUS_STORAGE_TSDB_RETENTION_TIME=2d
      - PROMETHEUS_STORAGE_TSDB_RETENTION=2d
      - PROMETHEUS_STORAGE_TSDB_RETENTION_SIZE=1GB
      - PROMETHEUS_STORAGE_TSDB_NO_FREELIST_SYNC=true
      - PROMETHEUS_STORAGE_TSDB_NO_VACUUM=true
      - PROMETHEUS_STORAGE_TSDB_WAL_COMPRESSION=true
      - PROMETHEUS_STORAGE_TSDB_WAL_COMPRESSION_LEVEL=snappy
      - PROMETHEUS_STORAGE_TSDB_WAL_COMPRESSION_SIZE=100MB
      - PROMETHEUS_STORAGE_TSDB_WAL_FSYNC_ON_FLUSH=true
      - PROMETHEUS_STORAGE_TSDB_WAL_MAX_SEGMENTS=1000
      - PROMETHEUS_STORAGE_TSDB_WAL_MAX_SIZE=1GB
      - PROMETHEUS_STORAGE_TSDB_WAL_NO_FREELIST_SYNC=true
      - PROMETHEUS_STORAGE_TSDB_WAL_NO_VACUUM=true
      - PROMETHEUS_STORAGE_TSDB_WAL_TRUNCATE_FREQUENCY=1h
      - PROMETHEUS_STORAGE_TSDB_WAL_FSYNC_ON_FLUSH=true
      - PROMETHEUS_STORAGE_TSDB_WAL_FSYNC_ON_CLOSE